chartConfig:
  config:
    eChartsConfig:
      series:
        - areaStyle: {}
          encode:
            xRef:
              field: events_date_day
            yRef:
              field: events_count
              pivotValues:
                - field: events_event_tier
                  value: High
          stack: events_count
          type: line
          yAxisIndex: 0
        - areaStyle: {}
          encode:
            xRef:
              field: events_date_day
            yRef:
              field: events_count
              pivotValues:
                - field: events_event_tier
                  value: Low
          stack: events_count
          type: line
          yAxisIndex: 0
        - areaStyle: {}
          encode:
            xRef:
              field: events_date_day
            yRef:
              field: events_count
              pivotValues:
                - field: events_event_tier
                  value: Very high
          stack: events_count
          type: line
          yAxisIndex: 0
      showAxisTicks: false
    layout:
      flipAxes: false
      stack: stack
      xField: events_date_day
      yField:
        - events_count
  type: cartesian
contentType: chart
description: Daily event count shown as stacked area chart.
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensionOverrides: {}
  dimensions:
    - events_event_tier
    - events_date_day
  exploreName: events
  filters: {}
  limit: 500
  metricOverrides: {}
  metrics:
    - events_count
  sorts:
    - descending: false
      fieldId: events_event_tier
  tableCalculations: []
name: Copy of day, stacked
pivotConfig:
  columns:
    - events_event_tier
slug: copy-of-day-stacked
spaceSlug: jaffle-shop
tableConfig:
  columnOrder:
    - events_event_tier
    - events_date_day
    - events_count
tableName: events
verification: null
version: 1
