chartConfig:
  config:
    eChartsConfig:
      series:
        - encode:
            xRef:
              field: events_date_day
            yRef:
              field: events_count
          markLine:
            data:
              - label:
                  position: end
                lineStyle:
                  color: "#000"
                type: average
                uuid: 923bc38f-4750-42c8-98d7-f536cf5a0d34
            lineStyle:
              color: "#000"
              type: solid
              width: 3
            symbol: none
          type: bar
          yAxisIndex: 0
      showAxisTicks: false
    layout:
      xField: events_date_day
      yField:
        - events_count
  type: cartesian
contentType: chart
description: >-
  The chart illustrates the daily count of events, highlighting trends and
  fluctuations over time.
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensionOverrides: {}
  dimensions:
    - events_event_tier
    - events_date_day
  exploreName: events
  filters: {}
  limit: 500
  metricOverrides: {}
  metrics:
    - events_count
  sorts:
    - descending: false
      fieldId: events_event_tier
  tableCalculations: []
name: day ref
slug: day-ref
spaceSlug: jaffle-shop
tableConfig:
  columnOrder:
    - events_event_tier
    - events_date_day
    - events_count
tableName: events
verification: null
version: 1
