chartConfig:
  config:
    eChartsConfig:
      series:
        - encode:
            xRef:
              field: events_date_day
            yRef:
              field: events_count
          stack: stack1
          stackLabel:
            show: true
          type: bar
          yAxisIndex: 0
      showAxisTicks: false
    layout:
      xField: events_date_day
      yField:
        - events_count
  type: cartesian
contentType: chart
description: Daily event distribution showing percentage of each event tier.
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensionOverrides: {}
  dimensions:
    - events_event_tier
    - events_date_day
  exploreName: events
  filters: {}
  limit: 500
  metricOverrides: {}
  metrics:
    - events_count
  sorts:
    - descending: false
      fieldId: events_event_tier
  tableCalculations: []
name: day stacked 100% refs
slug: day-stacked-100-refs
spaceSlug: jaffle-shop
tableConfig:
  columnOrder:
    - events_event_tier
    - events_date_day
    - events_count
tableName: events
verification: null
version: 1
