chartConfig:
  config: null
  type: table
contentType: chart
description: Tests NULL and NOT_NULL operators on boolean fields
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensionOverrides: {}
  dimensions:
    - subscriptions_is_active
  exploreName: subscriptions
  filters:
    dimensions:
      id: boolean-null
      or:
        - id: "1"
          operator: isNull
          target:
            fieldId: subscriptions_is_active
        - id: "2"
          operator: notNull
          target:
            fieldId: subscriptions_is_active
  limit: 500
  metricOverrides: {}
  metrics:
    - subscriptions_total_subscriptions
  sorts:
    - descending: false
      fieldId: subscriptions_is_active
  tableCalculations: []
name: "[Filter Test] Boolean - Null"
slug: filter-test-boolean-null
spaceSlug: test-sql-generation/filters
tableConfig:
  columnOrder:
    - subscriptions_is_active
    - subscriptions_total_subscriptions
tableName: subscriptions
verification: null
version: 1
