chartConfig:
  config: null
  type: table
contentType: chart
description: Tests EQUALS, NOT_EQUALS, IN_BETWEEN on YEAR interval
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensionOverrides: {}
  dimensions:
    - orders_order_date_year
  exploreName: orders
  filters:
    dimensions:
      and:
        - id: "1"
          operator: equals
          target:
            fieldId: orders_order_date_year
          values:
            - "2024-01-01"
        - id: "2"
          operator: notEquals
          target:
            fieldId: orders_order_date_year
          values:
            - "2022-01-01"
        - id: "3"
          operator: inBetween
          target:
            fieldId: orders_order_date_year
          values:
            - "2023-01-01"
            - "2025-01-01"
      id: date-basic-year
  limit: 500
  metricOverrides: {}
  metrics:
    - orders_unique_order_count
  sorts:
    - descending: false
      fieldId: orders_order_date_year
  tableCalculations: []
name: "[Filter Test] Date - Basic (YEAR)"
slug: filter-test-date-basic-year
spaceSlug: test-sql-generation/filters
tableConfig:
  columnOrder:
    - orders_order_date_year
    - orders_unique_order_count
tableName: orders
verification: null
version: 1
