chartConfig:
  config: null
  type: table
contentType: chart
description: Tests EQUALS true, EQUALS false
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensionOverrides: {}
  dimensions:
    - orders_is_completed
  exploreName: orders
  filters:
    dimensions:
      id: boolean-all
      or:
        - id: "1"
          operator: equals
          target:
            fieldId: orders_is_completed
          values:
            - true
        - id: "2"
          operator: equals
          target:
            fieldId: orders_is_completed
          values:
            - false
  limit: 500
  metricOverrides: {}
  metrics:
    - orders_unique_order_count
  sorts:
    - descending: false
      fieldId: orders_is_completed
  tableCalculations: []
name: "[Filter Test] Boolean - All Operators"
slug: filter-test-boolean-all-operators
spaceSlug: test-sql-generation/filters
tableConfig:
  columnOrder:
    - orders_is_completed
    - orders_unique_order_count
tableName: orders
verification: null
version: 1
