chartConfig:
  config: null
  type: table
contentType: chart
description: Tests NULL and NOT_NULL operators on date fields
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensionOverrides: {}
  dimensions:
    - orders_order_date_day
  exploreName: orders
  filters:
    dimensions:
      id: date-null
      or:
        - id: "1"
          operator: isNull
          target:
            fieldId: orders_order_date_day
        - id: "2"
          operator: notNull
          target:
            fieldId: orders_order_date_month
  limit: 500
  metricOverrides: {}
  metrics:
    - orders_unique_order_count
  sorts:
    - descending: false
      fieldId: orders_order_date_day
  tableCalculations: []
name: "[Filter Test] Date - Null"
slug: filter-test-date-null
spaceSlug: test-sql-generation/filters
tableConfig:
  columnOrder:
    - orders_order_date_day
    - orders_unique_order_count
tableName: orders
verification: null
version: 1
