chartConfig:
  config: null
  type: table
contentType: chart
description: A single value of the total number of orders received in June
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensionOverrides: {}
  dimensions:
    - orders_order_date_month
  exploreName: orders
  filters:
    dimensions:
      and:
        - id: f00cfea4-0c92-4bac-b6fd-462b199f3db2
          operator: equals
          target:
            fieldId: orders_order_date_month
          values:
            - "2024-06-01T00:00:00Z"
      id: 9e696bbe-6ef9-4352-94cc-5a297efd965a
  limit: 500
  metricOverrides: {}
  metrics:
    - orders_total_order_amount
    - orders_completed_order_count
  sorts:
    - descending: false
      fieldId: orders_completed_order_count
  tableCalculations: []
name: How many orders did we get in June?
slug: how-many-orders-did-we-get-in-june
spaceSlug: jaffle-shop
tableConfig:
  columnOrder:
    - orders_order_date_month
    - orders_total_order_amount
    - orders_completed_order_count
tableName: orders
verification: null
version: 1
