chartConfig:
  config:
    columns: {}
    conditionalFormattings:
      - color: "#63c654"
        rules:
          - id: 2f4bf13c-861b-41e7-bad8-7f553fb93197
            operator: greaterThan
            values:
              - 300
        target:
          fieldId: payments_total_revenue
    hideRowNumbers: false
    metricsAsRows: false
    showColumnCalculation: true
    showResultsTotal: false
    showRowCalculation: true
    showTableNames: false
  type: table
contentType: chart
description: A pivot table sample
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensionOverrides: {}
  dimensions:
    - payments_payment_method
    - customers_created_month
  exploreName: payments
  filters: {}
  limit: 500
  metricOverrides: {}
  metrics:
    - payments_total_revenue
  sorts:
    - descending: false
      fieldId: customers_created_month
  tableCalculations: []
name: How much revenue do we have per payment method each month?
pivotConfig:
  columns:
    - payments_payment_method
slug: how-much-revenue-do-we-have-per-payment-method-each-month
spaceSlug: jaffle-shop
tableConfig:
  columnOrder:
    - payments_payment_method
    - customers_created_month
    - payments_total_revenue
tableName: payments
verification: null
version: 1
