chartConfig:
  config:
    eChartsConfig:
      series:
        - encode:
            xRef:
              field: orders_order_date_day
            yRef:
              field: orders_unique_order_count
          type: line
          yAxisIndex: 0
        - encode:
            xRef:
              field: orders_order_date_day
            yRef:
              field: cumulative_order_count
          type: line
          yAxisIndex: 0
    layout:
      xField: orders_order_date_day
      yField:
        - orders_unique_order_count
        - cumulative_order_count
  type: cartesian
contentType: chart
description: Time series of orders received per day and total orders over time
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensionOverrides: {}
  dimensions:
    - orders_order_date_day
  exploreName: orders
  filters: {}
  limit: 500
  metricOverrides: {}
  metrics:
    - orders_unique_order_count
  sorts:
    - descending: false
      fieldId: orders_order_date_day
  tableCalculations:
    - displayName: Cumulative order count
      name: cumulative_order_count
      sql: |-
        SUM(${orders.unique_order_count})
        OVER(ORDER BY ${orders.order_date_day})
name: How many orders we have over time ?
slug: how-many-orders-we-have-over-time
spaceSlug: jaffle-shop
tableConfig:
  columnOrder:
    - orders_order_date_day
    - orders_unique_order_count
    - cumulative_order_count
tableName: orders
verification: null
version: 1
