chartConfig:
  config:
    eChartsConfig:
      series:
        - encode:
            xRef:
              field: amount_range
            yRef:
              field: orders_total_order_amount
          type: bar
          yAxisIndex: 0
    layout:
      flipAxes: false
      xField: amount_range
      yField:
        - orders_total_order_amount
  type: cartesian
contentType: chart
description: Payment range by amount
metricQuery:
  additionalMetrics: []
  customDimensions:
    - binNumber: 5
      binType: fixed_number
      dimensionId: payments_amount
      id: amount_range
      name: amount range
      table: payments
      type: bin
  dimensionOverrides: {}
  dimensions:
    - amount_range
    - payments_payment_method
  exploreName: payments
  filters: {}
  limit: 500
  metricOverrides: {}
  metrics:
    - orders_total_order_amount
  sorts:
    - descending: true
      fieldId: orders_total_order_amount
  tableCalculations: []
name: How do payment methods vary across different amount ranges?
pivotConfig:
  columns:
    - payments_payment_method
slug: how-do-payment-methods-vary-across-different-amount-ranges
spaceSlug: jaffle-shop
tableConfig:
  columnOrder:
    - amount_range
    - amount range
    - orders_total_order_amount
    - payments_payment_method
tableName: payments
verification: null
version: 1
