chartConfig:
  config:
    eChartsConfig:
      series:
        - encode:
            xRef:
              field: payments_payment_method
            yRef:
              field: payments_total_revenue
          type: bar
          yAxisIndex: 0
        - encode:
            xRef:
              field: payments_payment_method
            yRef:
              field: payments_unique_payment_count
          type: bar
          yAxisIndex: 0
    layout:
      flipAxes: true
      xField: payments_payment_method
      yField:
        - payments_total_revenue
        - payments_unique_payment_count
  type: cartesian
contentType: chart
description: >-
  Total revenue received via coupons, gift cards, bank transfers, and credit
  cards
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensionOverrides: {}
  dimensions:
    - payments_payment_method
  exploreName: payments
  filters: {}
  limit: 10
  metricOverrides: {}
  metrics:
    - payments_total_revenue
    - payments_unique_payment_count
  sorts:
    - descending: false
      fieldId: payments_total_revenue
  tableCalculations: []
name: How much revenue do we have per payment method?
slug: how-much-revenue-do-we-have-per-payment-method
spaceSlug: jaffle-shop
tableConfig:
  columnOrder:
    - payments_payment_method
    - payments_total_revenue
    - payments_unique_payment_count
tableName: payments
verification: null
version: 1
