chartConfig:
  config:
    eChartsConfig:
      series:
        - encode:
            xRef:
              field: visit_analytics_visit_date_month
            yRef:
              field: visit_analytics_total_visits
              pivotValues:
                - field: visit_analytics_bmi_category
                  value: Normal
          markLine:
            data:
              - label:
                  position: end
                lineStyle:
                  color: "#000"
                type: average
                uuid: fc2ebc47-6caa-4907-9c36-52577953ce93
            lineStyle:
              color: "#000"
              type: solid
              width: 3
            symbol: none
          type: bar
          yAxisIndex: 0
        - encode:
            xRef:
              field: visit_analytics_visit_date_month
            yRef:
              field: visit_analytics_total_visits
              pivotValues:
                - field: visit_analytics_bmi_category
                  value: Obese
          markLine:
            data:
              - label:
                  position: end
                lineStyle:
                  color: "#000"
                type: average
                uuid: 54647700-46e9-4133-a8c3-82b430919d46
            lineStyle:
              color: "#000"
              type: solid
              width: 3
            symbol: none
          type: bar
          yAxisIndex: 0
        - encode:
            xRef:
              field: visit_analytics_visit_date_month
            yRef:
              field: visit_analytics_total_visits
              pivotValues:
                - field: visit_analytics_bmi_category
                  value: Overweight
          markLine:
            data:
              - label:
                  position: end
                lineStyle:
                  color: "#000"
                type: average
                uuid: f8864169-14cb-4c66-952e-06070a5b64e1
            lineStyle:
              color: "#000"
              type: solid
              width: 3
            symbol: none
          type: bar
          yAxisIndex: 0
      showAxisTicks: false
    layout:
      flipAxes: true
      xField: visit_analytics_visit_date_month
      yField:
        - visit_analytics_total_visits
  type: cartesian
contentType: chart
description: Monthly visit analytics with alternative visualization.
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensionOverrides: {}
  dimensions:
    - visit_analytics_visit_date_month
    - visit_analytics_bmi_category
  exploreName: visit_analytics
  filters: {}
  limit: 500
  metricOverrides: {}
  metrics:
    - visit_analytics_total_visits
  sorts:
    - descending: false
      fieldId: visit_analytics_bmi_category
  tableCalculations: []
name: " month"
pivotConfig:
  columns:
    - visit_analytics_bmi_category
slug: month-2
spaceSlug: jaffle-shop
tableConfig:
  columnOrder:
    - visit_analytics_visit_date_month
    - visit_analytics_bmi_category
    - visit_analytics_total_visits
tableName: visit_analytics
verification: null
version: 1
