chartConfig:
  config:
    eChartsConfig:
      series:
        - encode:
            xRef:
              field: orders_status
            yRef:
              field: orders_total_non_completed_order_amount
          type: bar
          yAxisIndex: 0
      showAxisTicks: false
    layout:
      xField: orders_status
      yField:
        - orders_total_non_completed_order_amount
  type: cartesian
contentType: chart
description: Total non-completed order amount by status for a specific date
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensionOverrides: {}
  dimensions:
    - orders_status
  exploreName: orders
  filters:
    dimensions:
      and:
        - id: 7f94532b-8565-4afc-a64e-16249e97ad04
          operator: equals
          target:
            fieldId: orders_order_date
          values:
            - "2024-04-01"
      id: 51249dd2-52c3-4ecf-aa86-3566bfe7856b
  limit: 500
  metricOverrides: {}
  metrics:
    - orders_total_non_completed_order_amount
  sorts:
    - descending: false
      fieldId: orders_status
  tableCalculations: []
name: Order amount by status (filtered date)
slug: order-amount-by-status-filtered
spaceSlug: jaffle-shop
tableConfig:
  columnOrder:
    - orders_status
    - orders_total_non_completed_order_amount
tableName: orders
verification: null
version: 1
