chartConfig:
  config:
    eChartsConfig:
      series:
        - areaStyle: {}
          encode:
            xRef:
              field: orders_order_date_year
            yRef:
              field: orders_total_order_amount
              pivotValues:
                - field: orders_shipping_method
                  value: standard
          stack: orders_total_order_amount
          type: line
          yAxisIndex: 0
        - areaStyle: {}
          encode:
            xRef:
              field: orders_order_date_year
            yRef:
              field: orders_total_order_amount
              pivotValues:
                - field: orders_shipping_method
                  value: overnight
          stack: orders_total_order_amount
          type: line
          yAxisIndex: 0
        - areaStyle: {}
          encode:
            xRef:
              field: orders_order_date_year
            yRef:
              field: orders_total_order_amount
              pivotValues:
                - field: orders_shipping_method
                  value: express
          stack: orders_total_order_amount
          type: line
          yAxisIndex: 0
      showAxisTicks: false
    layout:
      flipAxes: false
      stack: stack100
      xField: orders_order_date_year
      yField:
        - orders_total_order_amount
  type: cartesian
contentType: chart
description: Yearly order amounts by shipping method as 100% stacked area.
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensionOverrides: {}
  dimensions:
    - orders_order_date_year
    - orders_shipping_method
  exploreName: orders
  filters: {}
  limit: 500
  metricOverrides: {}
  metrics:
    - orders_total_order_amount
  sorts:
    - descending: true
      fieldId: orders_total_order_amount
  tableCalculations: []
name: orders area 100% year
pivotConfig:
  columns:
    - orders_shipping_method
slug: orders-area-100-year
spaceSlug: jaffle-shop
tableConfig:
  columnOrder:
    - orders_order_date_year
    - orders_shipping_method
    - orders_total_order_amount
tableName: orders
verification: null
version: 1
