chartConfig:
  config:
    eChartsConfig:
      series:
        - encode:
            xRef:
              field: events_date_quarter
            yRef:
              field: events_count
          markLine:
            data:
              - label:
                  position: end
                lineStyle:
                  color: "#000"
                type: average
                uuid: 1efccfc1-29a2-47f6-85de-548876213ce8
            lineStyle:
              color: "#000"
              type: solid
              width: 3
            symbol: none
          type: bar
          yAxisIndex: 0
      showAxisTicks: false
    layout:
      xField: events_date_quarter
      yField:
        - events_count
  type: cartesian
contentType: chart
description: Quarterly event count showing trends over time.
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensionOverrides: {}
  dimensions:
    - events_event_tier
    - events_date_quarter
  exploreName: events
  filters: {}
  limit: 500
  metricOverrides: {}
  metrics:
    - events_count
  sorts:
    - descending: false
      fieldId: events_event_tier
  tableCalculations: []
name: quarter
slug: quarter
spaceSlug: jaffle-shop
tableConfig:
  columnOrder:
    - events_event_tier
    - events_date_quarter
    - events_count
tableName: events
verification: null
version: 1
