chartKind: table
config:
  columns: {}
  display: {}
  metadata:
    version: 1
  type: table
contentType: sql_chart
description: Updated description 2026-05-14T13:14:12.411Z
limit: 500
name: SQL Chart E2E Update Test
slug: sql-chart-e2e-update-1778764452393
spaceSlug: jaffle-shop
sql: SELECT * FROM "postgres"."jaffle"."payments" LIMIT 5
version: 1
