chartConfig:
  config: null
  type: table
contentType: chart
description: Tests PERCENT_OF_PREVIOUS_VALUE table calculation template
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensionOverrides: {}
  dimensions:
    - orders_order_date_month
  exploreName: orders
  filters: {}
  limit: 500
  metricOverrides: {}
  metrics:
    - orders_total_order_amount
  sorts:
    - descending: false
      fieldId: orders_order_date_month
  tableCalculations:
    - displayName: Percent of Previous
      format:
        type: percent
      name: percent_of_previous
      template:
        fieldId: orders_total_order_amount
        orderBy:
          - fieldId: orders_order_date_month
            order: asc
        type: percent_of_previous_value
name: "[TC Test] Percent of Previous Value"
slug: tc-test-percent-of-previous-value
spaceSlug: test-sql-generation/table-calculations
tableConfig:
  columnOrder:
    - orders_order_date_month
    - orders_total_order_amount
    - percent_of_previous
tableName: orders
verification: null
version: 1
