chartConfig:
  config:
    eChartsConfig:
      series:
        - encode:
            xRef:
              field: customers_customer_id
            yRef:
              field: orders_average_order_size
          type: bar
          yAxisIndex: 0
    layout:
      flipAxes: true
      xField: customers_customer_id
      yField:
        - orders_average_order_size
  type: cartesian
contentType: chart
description: Average order size for each customer id
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensionOverrides: {}
  dimensions:
    - customers_customer_id
  exploreName: orders
  filters: {}
  limit: 500
  metricOverrides: {}
  metrics:
    - orders_average_order_size
  sorts:
    - descending: true
      fieldId: orders_average_order_size
  tableCalculations: []
name: What's the average spend per customer?
slug: what-s-the-average-spend-per-customer
spaceSlug: jaffle-shop
tableConfig:
  columnOrder:
    - customers_customer_id
    - orders_average_order_size
tableName: orders
verification: null
version: 1
